### ISSUE TITLE
Bloqueo de TOR

### ISSUE THREAD

**Issue by joseaguardia** [Cluster-Va-Cluster-Viene/documentacion#1]
Buenas!

Todo este tema es superinteresante y realmente útil. Muchas gracias por compartir.

En el script del bloqueo creo que hay un pequeño error en:
`cat /tmp/full.tor | uniq | sort | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`

El sort debería ir antes del uniq, si no uniq no elimina los repetidos. Mira la diferencia:
![imagen](https://user-images.githubusercontent.com/16305835/99120432-26a07100-25fb-11eb-822c-14f31579e147.png)

Un saludo!

**Comment by GoldraK** [comment]
Buenas, 
gracias por el aviso, lo cambio ahora mismo 

Te debo una 🍺

Un saludo.
